[package]
name = "migrations"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm-migration = { version = "1", features = ["runtime-tokio-native-tls", "sqlx-sqlite"] }
sea-orm = { version = "1", features = ["runtime-tokio-native-tls", "sqlx-sqlite"] }
sea-query = "0.32"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
